### ISSUE TITLE
🐛 Support for more Date Formats in Frontmatter Fields

### ISSUE THREAD

**Issue by MMoMM-org** [jparkerweb/rich-foot#52]
**Describe the bug**
Rich Foot can't parse the date format I'm using for updated / modified:

YYYY-MM-DD HH:mm

On a different note I would like to customize also the way how Rich Foot displays the modified and created Date.

**To Reproduce**
- Add a field to frontmatter with 2024-12-26 17:48
- Configure that field as being used by Rich Foot as Updated

**Expected behavior**
Rich foot should be able to parse the date / time and not display NaN undefined NaN

**Comment by jparkerweb** [comment]
@MMoMM-org please update the plugin in Obsidian.

Your example date/time of `2024-12-26 17:48`, as well as others I tried, should now be able to be converted/formatted for display in the created/modified section of Rich Foot.

Thank you for the issue, and Happy Holidays.

**Comment by MMoMM-org** [comment]
it works now. but to be honest IMHO you are "holding" it wrong.
Instead of trying to code a lot of logic into your code you should let the user decide which format he want's to have:
- for the Date fields
- for the output fields
I like the default approach, helps a lot of people, but some people (me included) just don't work the default way.
So it would be nice if you could add a custom format part for:
- the date fields to find the information needed
- the output fields to display the information in a way which is wanted.

Do you want me to create a FR for that?

Thanks for the quick fix and I hope you had some Happy Holidays.

**Comment by jparkerweb** [comment]
@MMoMM-org 
Sure, please create a full spec of what would be your "perfect" setup for frontmatter dates and their display in rich-foot.
This has been an every evolving project :), as I originally just wrote some css/javascript to display the file create/modified dates I was able to get from Obsidian for myself. It turned into this plugin since I thought it could be helpful for others.  The addition of being able to use custom frontmatter fields for defining the custom/modifed dates is actually pretty new.

Please consider joining our Discord, as we could discuss this in a more fluid format, etc.
[Discord Invite/Link](https://discord.gg/sp8AQQhMJ7)

Either way, thanks again for your input and taking the time to support me 🍻
